motor_to_corexy:
  ros__parameters:
    pulley_radius: 0.00673
    x_limits:
      - -0.1475
      - 0.1475
    y_limits:
      - -0.13
      - 0.13

distance_to_radians:
  ros__parameters:
    pulley_radius: 0.00673
    x_limits:
      - -0.1475
      - 0.1475
    y_limits:
      - -0.13
      - 0.13
